# .github/workflows/pipeline.yml
name: House Price Prediction Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run pipeline
        run: |
          python pipeline.py
      #- name: Deploy model
        #run: |
        #  joblib.dump(model, 'house_price_model.joblib')
          